SELECT
    P.BRAND__C,
    N.PRODUCTCODE__C,
    P.PRODUCT_CATEGORY__C,
    N.PRODUCT_NAME__C,
    P.METER_TYPE__C,
    P.MARKET_CLASS__C,
    TO_VARCHAR(CURRENT_DATE, 'MMDDYYYY') || '_UNB' AS EFL_VERSION_CONTROL__C,
    P.ELF_LOAD_FACTOR__C,
    P.Electric_Vehicle__C,
    N."Term__C" AS PRODUCT_TERM__C,
    P.DO_NOT_ALLOW_TRANSFER__C,
    P.TDSP__C,
    P.GRACE_PERIOD_DAYS__C,
    P.PRICE_TYPE__C,
    P.RENEWABLE_ENERGY_PERCENTAGE__C,
    P.PROTECTED_PRODUCT__C,
    P.POLR_PRODUCT__C,
    P.MONTHS_OF_DISCOUNT__C,
    P.DISCOUNT_START_CYCLE__C,
    P.DISCOUNT_END_CYCLE__C,
    P.DISCOUNT_DESC_ENGLISH__C AS DISCOUNT_DESCRIPTION_ENGLISH__C,
    P.DISCOUNT_DESC_SPANISH__C AS DISCOUNT_DESCRIPTION_SPANISH__C,
    P.SKIP_SD_CALCULATION__C,
    P.DRG_PRODUCT__C,
    P.EFL_TEMPLATE__C,
    P.PRODUCT_CONTENT__C,
    P.TPV_FAMILY__C,
    CASE
        WHEN P.PRODUCT_NAME_SM__C IS NULL
            THEN NULL
        ELSE RTRIM(REPLACE(P.PRODUCT_NAME_SM__C,
                           ' ' || CAST(P.PRODUCT_TERM__C AS NVARCHAR),
                           ''))
                 || ' ' || TO_VARCHAR(N."Term__C")
    END AS PRODUCT_NAME_SM__C,
    P.PRODUCT_NAME_SM__C AS ORIGINAL_PRODUCT_NAME_SM__C,
    P.ELIGIBLE_PROD_EXCL__C,
    P.PRE_PAY_PRODUCT__C,
    P.MIGRATED_PRODUCT__C,
    P.PRODUCT_GROUP__C,
    P.PRUDENCY_FACTOR__C,
    P.DEMAND_TYPE_METER__C,
    P.CRITICAL_CARE__C,
    P.ABACUS_FAMILY__C,
    P.PREMISE_TYPE__C,
    'BLOCKED EDIT' AS PRODUCT_STATUS__C
FROM "XV1S"."CREATE_NEW_VBB_PRODS" N
JOIN "SFDC"."CXT_SFDC_PRODUCT_MASTER" P
    ON N.EXISTING_PRODUCTCODE__C = P.PRODUCTCODE__C
ORDER BY
    P.BRAND__C,
    N.PRODUCT_NAME__C,
    N.PRODUCTCODE__C;
